---
title: "git_00"
author: "Kacey Bates"
date: "September 19, 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

'Twas brillig, and the slithy toves

Did gyre and gimble in the wabe;

All mimsy were the borogoves,

And the mome raths outgrabe.

"Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Whose woods these are I think I know.

His house is in the village though;

He will not see me stopping here

To watch his woods fill up with snow.

My little horse must think it queer

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,

Shining with all his might:

He did his best to make the sky

And the sea look blue and bright,

And this was odd, because it was

The middle of the night.  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Yet each man kills the thing he loves,

By each let this be heard,

Some do it with a bitter look,

Some with a flattering word,

The coward does it with a kiss,

The brave man with a sword!

Some kill their love when they are young,

And some when they are old;

Some strangle with the hands of Gold:

The kindest use a knife, because

The dead so soon grow cold.
